### PR TITLE
My first Commit to upload logo

### PR DESCRIPTION
**Pull request by ShanmukhaSrinivas**
Please inform me 
Is this ok or not

### CODE REVIEW

**Comment by ShanmukhaSrinivas** [comment]
Goto images and the file name is sattbi.jpg.jpg

**Comment by Saif-Shines** [comment]
That's Awesome.

**Comment by Saif-Shines** [comment]
@saiyerniakhil 

This image by @ShanmukhaSrinivas is cool. I think you should use the same to update the website. For now I'll be merging this commit with the master.

**Comment by ShanmukhaSrinivas** [comment]
Thank U Soo much

**Pull request merged**
